{{- if and .Values.hub.enabled .Values.hub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "p10logs.hub.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "p10logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
{{- end }}
